dist: trusty
sudo: false
language: python
python:
- '3.6'
cache:
  pip: true
deploy:
- provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: "$TRAVIS_BUILD_DIR/bundles/*"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
- provider: pypi
  user: adafruit-travis
  on:
    tags: true
  password:
    secure: WdVDbhLATqRd9mjNe7pc4zgaE7ckVdmILZQAq/XaytM0/S265ktlh532xa06oQPAhomHQQ7+AFFr25e+fttYAkuFjDwzbqEGZXKHvKYenVklJqwhJHKWP67Nvd1QRNiT9cw2+GxpaUuhad3Enrw+80SAyZqqJ2oA7hGyGXhdE0EkPGnZpjKTDQSWSMbudmr0PRRVj22iQEhiT1JdsKAB/rZB2ju2R7mkkkFcgyosNQMzjXQwBIPIe9whcD2TWxGRWGB4CDE5n7pRf44ahtkrIlH+5IUNvLbOsvtYU+3nRzwht9fY6yOB2CgSjV+NklzSVYEWgYNYqehCLwEPCOXq3X3lgaCtttzlb/gHBBLHSSppdP/gUg81ech/ZD0LSdDHrzkGNzjSshjcu4IecXEgyspjseEatmvjPK9xqsYavT6SNlBJBldW3aSyZv2wtBoVfDIficRQvigDnMAfPzvGG/O23idsx2Jix6TGc5WMpU7UMcoYODqZQj3PQNQUVpyfDpKCytMLNiLlAezH3YXNTgGBv7f5OhNhDb+dsiMjAvqK0Ie3dFOE3tJqK5eSAQsS0qcbRBrZuKa060kdfctutnHoODYEq+oIJ6s7r0IvLJvkhvKn5dNfg4YnzSiwAjh+o4iJyFUiEWAN/qWz10aVEbxTc18V+QIGOJeY9z7hRrY=
install:
- pip install -r requirements.txt
- pip install pylint circuitpython-build-tools Sphinx sphinx-rtd-theme
- pip install --force-reinstall pylint==1.9.2
script:
- pylint adafruit_vc0706.py
- ([[ ! -d "examples" ]] || pylint --disable=missing-docstring,invalid-name examples/*.py)
- circuitpython-build-bundles --filename_prefix adafruit-circuitpython-vc0706 --library_location
  .
- cd docs && sphinx-build -E -W -b html . _build/html && cd ..
